#/bin/bash -e
#adb uninstall --user 0 com.android.apps.tag
#adb uninstall --user 0 com.android.backupconfirm
#adb uninstall --user 0 com.android.bips
#adb uninstall --user 0 com.android.bluetooth
#adb uninstall --user 0 com.android.bluetoothmidiservice
#adb uninstall --user 0 com.android.bookmarkprovider
#adb uninstall --user 0 com.android.calculator2
#adb uninstall --user 0 com.android.calllogbackup
#adb uninstall --user 0 com.android.captiveportallogin
#adb uninstall --user 0 com.android.carrierconfig
#adb uninstall --user 0 com.android.carrierdefaultapp
#adb uninstall --user 0 com.android.certinstaller
#adb uninstall --user 0 com.android.companiondevicemanager
#adb uninstall --user 0 com.android.cts.ctsshim
#adb uninstall --user 0 com.android.cts.priv.ctsshim
#adb uninstall --user 0 com.android.defcontainer
#adb uninstall --user 0 com.android.documentsui
#adb uninstall --user 0 com.android.egg
#adb uninstall --user 0 com.android.emergency
#adb uninstall --user 0 com.android.externalstorage
#adb uninstall --user 0 com.android.facelock
#adb uninstall --user 0 com.android.hotwordenrollment.okgoogle
#adb uninstall --user 0 com.android.hotwordenrollment.tgoogle
#adb uninstall --user 0 com.android.hotwordenrollment.xgoogle
#adb uninstall --user 0 com.android.htmlviewer
#adb uninstall --user 0 com.android.incallui
#adb uninstall --user 0 com.android.inputdevices
#adb uninstall --user 0 com.android.keychain
#adb uninstall --user 0 com.android.LGSetupWizard
#adb uninstall --user 0 com.android.location.fused
#adb uninstall --user 0 com.android.managedprovisioning
#adb uninstall --user 0 com.android.mms
#adb uninstall --user 0 com.android.mms.service
#adb uninstall --user 0 com.android.mtp
#adb uninstall --user 0 com.android.nfc
#adb uninstall --user 0 com.android.pacprocessor
#adb uninstall --user 0 com.android.phone
#adb uninstall --user 0 com.android.printspooler
#adb uninstall --user 0 com.android.providers.blockednumber
#adb uninstall --user 0 com.android.providers.calendar
#adb uninstall --user 0 com.android.providers.contacts
#adb uninstall --user 0 com.android.providers.downloads
#adb uninstall --user 0 com.android.providers.downloads.ui
#adb uninstall --user 0 com.android.providers.media
#adb uninstall --user 0 com.android.providers.partnerbookmarks
#adb uninstall --user 0 com.android.providers.settings
#adb uninstall --user 0 com.android.providers.telephony
#adb uninstall --user 0 com.android.providers.userdictionary
#adb uninstall --user 0 com.android.proxyhandler
#adb uninstall --user 0 com.android.server.telecom
#adb uninstall --user 0 com.android.settings
#adb uninstall --user 0 com.android.settingsaccessibility
#adb uninstall --user 0 com.android.sharedstoragebackup
#adb uninstall --user 0 com.android.shell
#adb uninstall --user 0 com.android.statementservice
#adb uninstall --user 0 com.android.stk
#adb uninstall --user 0 com.android.storagemanager
#adb uninstall --user 0 com.android.systemui
#adb uninstall --user 0 com.android.vending
#adb uninstall --user 0 com.android.voicemailomtp
#adb uninstall --user 0 com.android.vpndialogs
#adb uninstall --user 0 com.android.wallpaper.livepicker
#adb uninstall --user 0 com.android.wallpaperbackup
#adb uninstall --user 0 com.android.wallpapercropper
#adb uninstall --user 0 com.crucialsoft.asm
#adb uninstall --user 0 com.crucialsoft.fido.client
#adb uninstall --user 0 com.crucialtec.uaf
#adb uninstall --user 0 com.google.android.apps.work.oobconfig
#adb uninstall --user 0 com.google.android.backuptransport
#adb uninstall --user 0 com.google.android.configupdater
#adb uninstall --user 0 com.google.android.ext.services
#adb uninstall --user 0 com.google.android.ext.shared
#adb uninstall --user 0 com.google.android.gms
#adb uninstall --user 0 com.google.android.gsf
#adb uninstall --user 0 com.google.android.onetimeinitializer
#adb uninstall --user 0 com.google.android.packageinstaller
#adb uninstall --user 0 com.google.android.printservice.recommendation
#adb uninstall --user 0 com.google.android.setupwizard
#adb uninstall --user 0 com.google.android.tts
#adb uninstall --user 0 com.google.android.webview
#adb uninstall --user 0 com.hy.system.fontserver
#adb uninstall --user 0 com.lge.android.atservice
#adb uninstall --user 0 com.lge.aodex
#adb uninstall --user 0 com.lge.app.floating.res
#adb uninstall --user 0 com.lge.appbox.client
#adb uninstall --user 0 com.lge.appwidget.dualsimstatus
#adb uninstall --user 0 com.lge.autosimlockservice
#adb uninstall --user 0 com.lge.bluetoothsetting
#adb uninstall --user 0 com.lge.bnr
#adb uninstall --user 0 com.lge.bnr.launcher
#adb uninstall --user 0 com.lge.camera
#adb uninstall --user 0 com.lge.cic.eden.service
#adb uninstall --user 0 com.lge.clock
#adb uninstall --user 0 com.lge.cloudhub
#adb uninstall --user 0 com.lge.concierge
#adb uninstall --user 0 com.lge.drive.activator
#adb uninstall --user 0 com.lge.drmservice
#adb uninstall --user 0 com.lge.easyhome
#adb uninstall --user 0 com.lge.effect
#adb uninstall --user 0 com.lge.eltest
#adb uninstall --user 0 com.lge.entitlementcheckservice
#adb uninstall --user 0 com.lge.eula
#adb uninstall --user 0 com.lge.eulaprovider
#adb uninstall --user 0 com.lge.exchange
#adb uninstall --user 0 com.lge.fmradio
#adb uninstall --user 0 com.lge.formmanager
#adb uninstall --user 0 com.lge.gallery.vr.wallpaper
#adb uninstall --user 0 com.lge.gametuner
#adb uninstall --user 0 com.lge.gba.android
#adb uninstall --user 0 com.lge.gcuv
#adb uninstall --user 0 com.lge.gestureanswering
#adb uninstall --user 0 com.lge.globalwfc
#adb uninstall --user 0 com.lge.gnss.airtest
#adb uninstall --user 0 com.lge.gnsspostest
#adb uninstall --user 0 com.lge.gnsstest
#adb uninstall --user 0 com.lge.hiddenmenu
#adb uninstall --user 0 com.lge.hiddenpersomenu
#adb uninstall --user 0 com.lge.homeselector
#adb uninstall --user 0 com.lge.hotspotprovision
#adb uninstall --user 0 com.lge.icecontacts
#adb uninstall --user 0 com.lge.iftttmanager
#adb uninstall --user 0 com.lge.ime
#adb uninstall --user 0 com.lge.ime.solution.handwriting
#adb uninstall --user 0 com.lge.ime.solution.text
#adb uninstall --user 0 com.lge.inputdevices
#adb uninstall --user 0 com.lge.intelligent
#adb uninstall --user 0 com.lge.laot
#adb uninstall --user 0 com.lge.launcher2.theme.optimus
#adb uninstall --user 0 com.lge.launcher3
#adb uninstall --user 0 com.lge.leccp
#adb uninstall --user 0 com.lge.lgdmsclient
#adb uninstall --user 0 com.lge.lgdrm.permission
#adb uninstall --user 0 com.lge.lgfmservice
#adb uninstall --user 0 com.lge.lgfota.permission
#adb uninstall --user 0 com.lge.lginstallservies
#adb uninstall --user 0 com.lge.lgmapui
#adb uninstall --user 0 com.lge.LGSetupView
#adb uninstall --user 0 com.lge.lockscreensettings
#adb uninstall --user 0 com.lge.lteconfig
#adb uninstall --user 0 com.lge.mlt
#adb uninstall --user 0 com.lge.mrg.service
#adb uninstall --user 0 com.lge.networksettings
#adb uninstall --user 0 com.lge.nextcapture
#adb uninstall --user 0 com.lge.NfcSettings
#adb uninstall --user 0 com.lge.phonemanagement
#adb uninstall --user 0 com.lge.privacylock
#adb uninstall --user 0 com.lge.provider.lockscreensettings
#adb uninstall --user 0 com.lge.provider.signboard
#adb uninstall --user 0 com.lge.provider.systemui
#adb uninstall --user 0 com.lge.rcs.sharedsketch
#adb uninstall --user 0 com.lge.sdencryption
#adb uninstall --user 0 com.lge.servicemenu
#adb uninstall --user 0 com.lge.shutdownmonitor
#adb uninstall --user 0 com.lge.signboard
#adb uninstall --user 0 com.lge.signboard.settings
#adb uninstall --user 0 com.lge.snappage
#adb uninstall --user 0 com.lge.springcleaning
#adb uninstall --user 0 com.lge.srtc
#adb uninstall --user 0 com.lge.sui.widget
#adb uninstall --user 0 com.lge.sync
#adb uninstall --user 0 com.lge.systemservice
#adb uninstall --user 0 com.lge.theme.blackgold
#adb uninstall --user 0 com.lge.theme.highcontrast
#adb uninstall --user 0 com.lge.theme.superbatterysaving
#adb uninstall --user 0 com.lge.themeservice
#adb uninstall --user 0 com.lge.themesquare
#adb uninstall --user 0 com.lge.touchcontrol
#adb uninstall --user 0 com.lge.videoplayer
#adb uninstall --user 0 com.lge.videostudio
#adb uninstall --user 0 com.lge.voicerecorder
#adb uninstall --user 0 com.lge.vragent
#adb uninstall --user 0 com.lge.vrplayer
#adb uninstall --user 0 com.lge.wallpaperpicker
#adb uninstall --user 0 com.lge.wapservice
#adb uninstall --user 0 com.lge.wfds.service.v3
#adb uninstall --user 0 com.lge.wifi.p2p
#adb uninstall --user 0 com.lge.wifisettings
#adb uninstall --user 0 com.qapp.secprotect
#adb uninstall --user 0 com.qualcomm.atfwd
#adb uninstall --user 0 com.qualcomm.location
#adb uninstall --user 0 com.qualcomm.location.XT
#adb uninstall --user 0 com.qualcomm.qcrilmsgtunnel
#adb uninstall --user 0 com.qualcomm.qti.qmmi
#adb uninstall --user 0 com.qualcomm.qti.radioconfiginterface
#adb uninstall --user 0 com.qualcomm.qti.telephonyservice
#adb uninstall --user 0 com.qualcomm.svi
#adb uninstall --user 0 com.qualcomm.timeservice
#adb uninstall --user 0 com.qualcomm.wfd.service
#adb uninstall --user 0 com.rsupport.rs.activity.lge.allinone
#adb uninstall --user 0 com.ti.server
#adb uninstall --user 0 com.uei.lg.quicksetsdk.irblaster
#adb uninstall --user 0 org.codeaurora.btmultisim
#adb uninstall --user 0 org.simalliance.openmobileapi.service
adb uninstall --user 0 com.android.calendar
adb uninstall --user 0 com.android.cellbroadcastreceiver
adb uninstall --user 0 com.android.chrome
adb uninstall --user 0 com.android.contacts
adb uninstall --user 0 com.android.gallery3d
adb uninstall --user 0 com.evernote
adb uninstall --user 0 com.evernote.promohelper
adb uninstall --user 0 com.facebook.appmanager
adb uninstall --user 0 com.facebook.katana
adb uninstall --user 0 com.facebook.system
adb uninstall --user 0 com.google.android.apps.docs
adb uninstall --user 0 com.google.android.apps.docs.editors.docs
adb uninstall --user 0 com.google.android.apps.docs.editors.sheets
adb uninstall --user 0 com.google.android.apps.docs.editors.slides
adb uninstall --user 0 com.google.android.apps.maps
adb uninstall --user 0 com.google.android.apps.photos
adb uninstall --user 0 com.google.android.apps.tachyon
adb uninstall --user 0 com.google.android.feedback
adb uninstall --user 0 com.google.android.gm
adb uninstall --user 0 com.google.android.googlequicksearchbox
adb uninstall --user 0 com.google.android.marvin.talkback
adb uninstall --user 0 com.google.android.music
adb uninstall --user 0 com.google.android.partnersetup
adb uninstall --user 0 com.google.android.syncadapters.calendar
adb uninstall --user 0 com.google.android.syncadapters.contacts
adb uninstall --user 0 com.google.android.videos
adb uninstall --user 0 com.google.android.youtube
adb uninstall --user 0 com.instagram.android
adb uninstall --user 0 com.lge.email
adb uninstall --user 0 com.lge.filemanager
adb uninstall --user 0 com.lge.friendsmanager
adb uninstall --user 0 com.lge.ia.task.incalagent
adb uninstall --user 0 com.lge.ia.task.informant
adb uninstall --user 0 com.lge.ia.task.s4urecommender
adb uninstall --user 0 com.lge.ia.task.smartcare
adb uninstall --user 0 com.lge.ia.task.smartsetting
adb uninstall --user 0 com.lge.lgaccount
adb uninstall --user 0 com.lge.lgworld
adb uninstall --user 0 com.lge.lifetracker
adb uninstall --user 0 com.lge.lockscreen.livewallpaper.cat
adb uninstall --user 0 com.lge.lockscreen.livewallpaper.kaleidoscope
adb uninstall --user 0 com.lge.music
adb uninstall --user 0 com.lge.musicshare
adb uninstall --user 0 com.lge.myplace
adb uninstall --user 0 com.lge.myplace.engine
adb uninstall --user 0 com.lge.qmemoplus
adb uninstall --user 0 com.lge.qremote
adb uninstall --user 0 com.lge.remote.lgairdrive
adb uninstall --user 0 com.lge.remote.setting
adb uninstall --user 0 com.lge.sizechangable.musicwidget.widget
adb uninstall --user 0 com.lge.sizechangable.weather
adb uninstall --user 0 com.lge.sizechangable.weather.platform
adb uninstall --user 0 com.lge.sizechangable.weather.theme.optimus
adb uninstall --user 0 com.lge.smartdoctor.webview
adb uninstall --user 0 com.lge.smartshare
adb uninstall --user 0 com.lge.smartshare.provider
adb uninstall --user 0 com.lge.smartsharepush
adb uninstall --user 0 com.lge.task
adb uninstall --user 0 com.lge.updatecenter
adb uninstall --user 0 com.lge.upsell
